/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface KpCode {}
  interface KpColorPalette {
    'colors': { hex: string; name: string; rgb: string; weight: string; }[];
  }
  interface KpColorRibbon {
    'colorHex': string;
    'colorName': string;
    'colorRgb': string;
    'colorWeight': string;
    'isCard': boolean;
  }
}

declare global {


  interface HTMLKpCodeElement extends Components.KpCode, HTMLStencilElement {}
  const HTMLKpCodeElement: {
    prototype: HTMLKpCodeElement;
    new (): HTMLKpCodeElement;
  };

  interface HTMLKpColorPaletteElement extends Components.KpColorPalette, HTMLStencilElement {}
  const HTMLKpColorPaletteElement: {
    prototype: HTMLKpColorPaletteElement;
    new (): HTMLKpColorPaletteElement;
  };

  interface HTMLKpColorRibbonElement extends Components.KpColorRibbon, HTMLStencilElement {}
  const HTMLKpColorRibbonElement: {
    prototype: HTMLKpColorRibbonElement;
    new (): HTMLKpColorRibbonElement;
  };
  interface HTMLElementTagNameMap {
    'kp-code': HTMLKpCodeElement;
    'kp-color-palette': HTMLKpColorPaletteElement;
    'kp-color-ribbon': HTMLKpColorRibbonElement;
  }
}

declare namespace LocalJSX {
  interface KpCode {}
  interface KpColorPalette {
    'colors'?: { hex: string; name: string; rgb: string; weight: string; }[];
  }
  interface KpColorRibbon {
    'colorHex'?: string;
    'colorName'?: string;
    'colorRgb'?: string;
    'colorWeight'?: string;
    'isCard'?: boolean;
  }

  interface IntrinsicElements {
    'kp-code': KpCode;
    'kp-color-palette': KpColorPalette;
    'kp-color-ribbon': KpColorRibbon;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'kp-code': LocalJSX.KpCode & JSXBase.HTMLAttributes<HTMLKpCodeElement>;
      'kp-color-palette': LocalJSX.KpColorPalette & JSXBase.HTMLAttributes<HTMLKpColorPaletteElement>;
      'kp-color-ribbon': LocalJSX.KpColorRibbon & JSXBase.HTMLAttributes<HTMLKpColorRibbonElement>;
    }
  }
}


